$ANSIBLE_VAULT;1.1;AES256
38666635376233633831333536346638646434643638666361336239333762373036316437363466
3331626563343261616264653764383535653166623730650a393837313630626437376565303866
63346131663034653662633132346231303139323031313138326432303833666563656462333465
6465336435616465360a373034623162386161643066363763303138383862336236313564626566
64613433383461353830343834636566306164306265666462623565393339656462326436366331
30353838656433353134343133373036383465656262656239653735313830386464616663326238
37303938313062306134663930383639623365323262653837623137636261363739373061613666
64346234393864623635
