$ANSIBLE_VAULT;1.1;AES256
30666665333363316233386666303061356537363439386564316462646662616632386236323731
3066646238303031623632373735363364663435653364330a643130333239343430613131363938
63613835326662353430626231383838633935396236656532623163393164393161303632333436
6561326463356264650a643162626135303763396163613131386637383761333961326434353734
31353462333865643335643539323430623138393634626138366239343135393636306335313134
64313935623639376334613138386663333336333131363538323166643036363663396431333434
36333732383162363435386432363161386136663833393638306335366530306164326664363637
37353430653336613834626662333061383134396262663739386633303963303538383735386461
34636639623836623061613933353665646234636636373539373832346632356461666161366538
31313333396333646134323034373666653934643465303439303466353961353062343132373265
31323235663630386365613737336438323334326331393565396139316264663232343633636134
35616166363436383062643339333939343563613066363461323339366365623537616431613836
66653931666361356563386364346537636266646462313830303431336661303636303139643435
3961336435613437326666316236326562326461396137373239
