$ANSIBLE_VAULT;1.1;AES256
64346334396336313265353964343635363039626161396664313132656131653230633039326664
6230373238373234303061323233613934653665356135620a303364623762386133613538326535
32646662623630616434356666326364373666383430326234356135663737663263346166336432
3765393431643630640a623539313037343438646134346131346165356639353036303432366364
66646234356237363332643761303336646230333332653931353564383961613265383036393161
33626132663461613065393736303135643931373932396231353761396332386338363837376435
39353931323637393266393261393638653536303533323530323232373065363539616566653339
62386666323063336163663033613734386163393835343535383166663536303834313330366563
65373233636362396535663934663935646438633936613362303438646437363130636432393166
66633263313163636537633636353764333563663365643666373333346136306663316265393061
66346131373737663838666164393435653937303364323239333231636631313332643534306661
37663938343930613939663564613732633665366639653562663235373366313761663330653430
39353462616439613035353030666162386436306532626433613236616138643162383137353564
3736353432316433393335353161356461396661333866393766
