$ANSIBLE_VAULT;1.1;AES256
38393838663839643230643431333431303734613265623465376564373764376563343062663765
3761663966323535343233623661333838383935323034630a333533383934393336356331333564
39643230313561346332306432633664313938343964656163616365636136316639316265303532
3663303336343361350a663465313239366434356531393638356166366364616332626362633930
38353838313763393930373339323838666163313262623563376262356532313936326131633465
36363936643633636339303164333564356332633732653235663632373836666334393432616664
33346266366436353738666131663839366139666137616139363066653832306239303432346564
32313033653265353430633165353566383638613262356465326164343165396464316238656563
63653234393963313463343363373130363463383434376337626433396135343761643063643264
64333231623462656165356230623631626436636561636165393466353164373933373030633063
38656334303733313838656662333730616130623163353930363463386131626539386337663336
38313333306234653333393633326434376338323336333430353632633134636433376432343136
33616532326662333638353565663763626131643336636631666562383761666233666233386237
34323961643362393739316262646330333237363031386163623063383466363930326466306334
37343235383963353135643936336438303533303030333832336334626162323030383264346366
34623833303136366638
