$ANSIBLE_VAULT;1.1;AES256
63373334323161316363366533333163326165396366363265656338386566333830663638323436
6332376634373636653837613135643035393732326362340a343735366534353235366262633162
37336661336338326631663439363831313433376130373562356562363536343239623833306636
3834373632626230310a663964386431656639623039313436383035633530643935346339313932
32303866333139336637626333373434396462393930386331306137346339366464376562663834
38646165643138323732373436346134363335613766633031633530316232333764613865393664
32383266306638633765373361306562323038386562623736383230333531323431306432356565
37323563663161386235366230363530646537653166666139396132386431303763373430656231
36333938663732356365323763303031393933303637346638313166366536633236663836376239
34343734666264653762653561383134303539623130343963363266653162346264616430306239
32356230363562663739393738663238356365366131383061666561613164663536383764336661
36393165316136386331613935663238633830663134363261393665303965363335343033643437
39623836663837316530303566643138316435386438363934346535616438356237393331663465
33303838363563366337396339313437663764303035353836633766313038396134383034623564
63356437633963666166353136353561343638643631336635396365316230383265663436313466
62663533643434613837
