$ANSIBLE_VAULT;1.1;AES256
64316462316361623831613661316537316636666564323836363131303537643732366339313533
3837373234356163626331393431613761356635383163610a376165326636393761643536386530
66366638623964616135646231396233306337356535393131303864343839636132383935326130
3466323838643565300a313161646661643833323739636665633537323766323132376333323165
64663939656335343462306465366665656462356132326365373237666263653430616362326436
34646134333437653632373530313538313162363336626136383034643962323137306163663163
36353836643266663437613834363037373964653335366133613534386361646666363763646231
31343138383031656432353332616565313033373334643665316531656639393064653762656630
31393763316234626365623363356630666566376537343637366263306165643933383561366262
63623033393766306339346264646534366130353039613430346539656535656364376534356337
62303236633735643762366239373061323339346261323262353862393432366431656539653437
62366463636264393637353032643065343130346661336630653934366366623536316562393064
37303837636630663835336538333032383163306536353438316438363032363836383861333031
64343836396661346531636566323962323330633264373961663061393634336434643437326466
39333733383135646130613466353239393931353862316438346664343566363230323930323336
61663162383363373261396165346164313165626465353230363935323030363038396135356437
6164
