$ANSIBLE_VAULT;1.1;AES256
61363336376132376232633433333632313033643335326363303463656430373436323164623766
3637383636633630303232313232623564646536623761310a616231613662613066623530326237
64323466376335303862663030353336623839356561363334663962386564636533356561353134
3935366130653634390a353838653964373064663765323739316363303834646166366265363865
65303232613162336666326233623837636133346166373864613465363663636365383031353331
39653830396465333662396139386464643135636139386535623762323132636532353034353932
39303539663637383930383865323733386534343066373366313139306232636265656564333933
33633162323537383461383832646436653962386535393832653965333839346532653439313938
62393262633130613535383363323136663836346433633639353431323031353633306233386233
31313730373637356639323963306439633864623433343037663631366238326164393165326665
34633135626331333335393834343862346465653935373633393230323132376335613534623836
31313461646131343630386535653934666339303532336633366466656437646337386561356339
64663431333035373836333066633535373639666631623061383438646534313537346364373664
63653835323466663963643130383463363935656530616161336333633561633465316531373935
39656632633135353563643765343937626531386165383732313732326431393264303233663136
65333333383564613336656462316335373138623965663061396361333433323764323561323831
36303432326630333439663831636431333032386566366235646236666463343966
