$ANSIBLE_VAULT;1.1;AES256
37323261613065613965613166373530646138633233346434383537643366663033613234363337
3637373964336261323832366339626564636332303532660a656362646162333937333461613763
63633732323338313466396332393535343533353033366638373361643562386331386339383564
6164623530616131340a636366376530373335313438333830383632343761643436373865303331
31656334366130373833363464623736333830313135613231653732366366366533363437343363
64303135633333336431623530386130626665633565316435336363366662383966383166653137
31653939616239386136393637373739386166383064613634323230343730356333366264663430
32623366626165373266393033636463333832356363343164626531616434336332323633366637
64613131373336373332613531323563346565373530333061333635313631643064623639383766
63663965306661666130616135333838623635663737326430366430356266336531343362326131
62653331636133333837646238366464386337353138366662643533373964353466323562623163
32636531663138393637333830623537303938653636656236663038353034633436346137383665
31316366326431323263653933643031646639363733643364666662656235336662366137353664
65346630383764346462343165353762373963343137313333393065386165616235643262323738
33636363396439643930303033323632343534633731316232323561643337633636383433386435
66356232303633643266376434353832623130356237353562353061323732313261343866666138
6433
