$ANSIBLE_VAULT;1.1;AES256
62373631363832393764373565316134396161316261303462356465626238313538613863656230
3162626333626462393365623835613439363236633637610a636637396562316661626166666637
31353531306134643366306265643737646262303431613331626162323039376361643939323637
3739336633376131390a396630636466373432613363646132353966306437393731613630626631
32313365373261363761633930656135343661366438373866653938666363346130
