$ANSIBLE_VAULT;1.1;AES256
33653736656131666662653764653739636632383261656537653062363265393439323832353834
3464653038613363316466656364373934383062316465620a623034643261613866303062303931
39623766643234623565663337316330353230363463393666643831323131313232383138306664
6232383766613465340a646537633935356137393864613234306434653536343531653933376635
35663334303630313330386364633661383161333133386261306664623666336664663565636465
38653739643037666634373634353661346339343331323965623432663431356536306133666161
63616262666535313033396263646638303266616632373764353566373065323337623238633263
37663937616461303164316664613565326438646530656362636565636132633839333661333831
61373365363036313339323139643462316366653637613133386665323962666666336539626164
35356161633463393162616137343832626561393332323465663335663137643265366165653336
35666639393135363235366130306533313966626139343933616432653134336365393664313761
63346366646531383939386163636463613662346166313830303836623939643664373830636164
32626232666332643339626166373234353364353039666237333633396533323530653362333834
64636437333032346663313134633134313666373464343934303863323063623365616533626166
66616662386263393864616366653764613330613962303563333732333163653431356564336334
37646434643330316161
