$ANSIBLE_VAULT;1.1;AES256
36303833393433336264393561333036393230633866306636373938323735366639303338373436
3833643037326432363464336634373131643263343932370a633866376261363834663732333864
63383163343963396439353032316230663363303762393663373439303761633237376539363835
6166666161396138310a396262383134333666353966316462663035343530636439346338636665
36623966346261333463643666373962336636636332656631623866313261333764366339303064
30613266623533613338373464636464366336393061626564323763653464663731343236343861
353862626231363061393236633130623862
