$ANSIBLE_VAULT;1.1;AES256
66323331636564366330343439326663646566613636313937393033646632653332356164373261
3965326437343964643334343462636437623264323534330a393230626534373462636338313139
37653935663132363939343035636436643066306238353234623533393738396334333862346538
3266633138393161640a363735383934353936326236333631666532346537653935393664353364
65373530626261643931346366383163366337333534303039646430323033646437393130343861
32393839663239346133643835393061626335323861343935343036313734636232303730303735
383839356134623336333632633037326662
