$ANSIBLE_VAULT;1.1;AES256
38626666303564373630633961633437313461353937303733653564306663313534636535646636
6334396335613363366336373036303134306636663361350a376638633234353134636531393031
39663130306637326439666331386631356363306332346431356138323038366132303436636137
6566313333363230630a383531313033613233636166373637366137666266363238643166346362
34396231653666646138663434313630383364346236616230616433386131656330613733386631
35383766366333356538313739613564666134323936306636353537303165343762306633313234
36656162316463643561353239643164623866363532376535636464353164643834386238316436
61376632663732616439643839613339313334343632663030656564636337623761303738316533
39303161323433303835386462346433373937363061353263626563616535336431666437616438
38333433643037633339376362626361643237313333343633623131636535636462303038373736
39663365663737623837373433613531313661376436653638386266323466333164346462666539
30323438643936366436396463646137393930313563633035313330643732633230613966303235
35393233386133366239623565626361643364303363616566636232316563316637653933333231
37353362383737653134393839353337303531623962623739376632306166313765373664316162
37613130616137626234356563393237343137316336633736326430376565373731393431383230
35313232303636376234636630316637353037356365376330636235633937623762396439636233
3138
