$ANSIBLE_VAULT;1.1;AES256
31616364616435323631653366653732396335393235323032373735653334333339616532333461
3636633162346432303363653761633861623662373935360a643234383434333464316632663635
33363061616638633931326531373236393362616530613466323531303032383433313432356464
3562333537306639370a363861343962326561396361633738653435313635346661646162616237
62663264323237323066376636656130376363323931643231626339383936313062383439326464
61326531313062386437323462626162646337373831323932333937343332663032363863336163
39663136663836333030386465343731393437373264323036386236323137636433333764383461
63656335313934346234356361393566386538323536373434643136343339323334353761346130
33323932366232376462336438383135636635303463306233636262646461663764333038626561
36323832393636666538633761336161393332623933326665303132336535393862373062396335
38303062633032313263353062336132623961613535336466383837376434316165383235656530
30363439633938363437303639383539623131316431316566383762333336656566346561626535
35383130666162396632376663373966336363616238343830373733656565636561613764323730
30333465356238373638303461336631333136343363663231376234353636663463383831383531
66653938643039393432616563633235623565643565333265386634343132356137313938306432
64613637373437323037306665366532663965353439616333373139393565373439383331653563
3233
