$ANSIBLE_VAULT;1.1;AES256
65646665376463343934316437373830646639346431303534343632323435643135656631323039
3830303836336566373562393431346335326364626436360a653439653238633831343132333637
61376336336665653764333065613539663933303861343162353664303165643235336638613866
3131356662346138320a313139393262306464383337616134653637643035663435396664623365
65616237393432633230353034613363356465623933616364636165646365313436623132316561
64326364623433323862366630376230313936373064313833646534386666326131623230316532
31633932633033623564313935376532613365666439396361343933396165336161613430666139
65633134383865646264643665323261336565383766396162323061656266636637396262313338
35313538366138303539623033646261393132383330343561396132336236376639396132653436
30636137646561306539366631303230666462623130646630353337393463386530633635333131
37323933373139336666353463353166333336643035626666336661633266323038626339363931
37633533373631343738373764346334656262633438333931636563636437623333386236336430
63656333633865363361333765373731393562346362636334653861333133653036613463333130
64363535396462623734373461356630666139363038636362613332323739316362383366643933
64316264616638346532306439643562666435336464656431303661383463313031396638626137
38626666646137666531653036643334323330343662613063303036393235393264623365363430
6664
