$ANSIBLE_VAULT;1.1;AES256
63653965333466323333333538636166626135346131636161386362633435356230623431383230
6264343439393332626234613135636230326637373836620a386566616132323432303430643961
30663264663131653963656633396263663537623761353533333331353463646664356138373830
3630386132656262620a383233303331383037393563633764386661363364373435613138303764
37383039383335623734303837313866626139333730303833633133353939316337613063666135
30643834663337616461663537353433316131366566306637333935616431663233626463633866
613765653131626261326337653864346137
