$ANSIBLE_VAULT;1.1;AES256
30663531353565343130306135663562343533626239343830623836666532653734383465643530
3161656338646464333265626364326437643337393037300a353233316665366661653461616638
37656633373435306165353030383664653239656430373437393234393563623932393161333634
6261643438393462310a343431376532616636356332353934646365613164363533323732386338
31646538393066343536626666323664393633393939633166366530343031373161613233336537
34663562353132343866633765383336356437353335386230366231653466636431356138653164
63623362383835346137633330363661383930666165613963336432393433663439323632346639
38366433396366363437633134343230663366316161303330306131336635626664346138336232
30326662626433613236613662386231313431333036336537373762633339326466363133633139
31616236323262393035643132386336393261376135316561343030383935333733326564616630
37333862613433343330363731303031613962336635633063313161623437616235663134643634
37663462633761306364646236633461653739626565323734343935633061666466363637393936
30633430363965363762656266346637646235613331623936626131376636363730663063313264
31333933333732303336623536623735636538313861326561326263363130353233313662303938
64666334333932356331396334346261323437653463626636396163326430333839353861303363
65343734653765376363
