$ANSIBLE_VAULT;1.1;AES256
30386530343831656239303564313163616464623230303534346666383966303232346561633465
3965393835323933623863656362396331643335343363370a373464633035353033376233306131
65646462616666623531666561663637376162343839326264366535353937623032646235646231
3362343463393861630a353162353930306261626461623832343038393762303863656663666434
31663862643764333134353662363032613335373764343363636564343632353233663438346535
30656635373466313431373238646432323862653639313436333036383233633131326130653263
33386633366436393035653039343235313436306566616562323463313433383639313036653432
38376665316662643861386265653937653534643235333839616333303465313437626166343733
38633136373636656164383532613631396661633435663736303436333637386436656563663335
37363933303130333438616464336162333638333434613332373330313062326335316137643366
36386161336131653834366130376262656632326664663364653238616336653539666366363164
62366630623638633536653932613939663239326264313465626664353832366639636236636337
39646234303839613631646137613337373338353665353838613966666634613237356335313035
66363263333332623338663661343330393431663561646233353564653130613735326632643734
38626230653561396438663662336133616130333532636364383933313563663832353064656433
33363137633338653735316361316361366263376361633061613733313932373339333535373339
3831
