$ANSIBLE_VAULT;1.1;AES256
64323864643439376466363364613264313039303430333834643736386630356630643031316132
3330363533666365376663666363323731643932373936620a626165373339306135663463376539
64316135623561323439393633346239386366623531336665613963393135666138373562333262
3735353837333061390a356166303834356137306533363939613164613264363131633434386264
61653965633138323163396664393566643834316566626536666364393636666235363231343930
61303539313335653939356435316664623638356334316463626262623133383361336361336238
33316235633733646633393335303936393366343437333365653332653365316531656162643063
64386165623736613335663165633633303361623739336562653964376532356562353037373035
66643532636139363761616232303433666635373465663863333763353638626663356364316161
36326539326130623036356132326235626565336664626363376131373338346136316463643533
38366135373137326435636334613831623131613366323265653239356539623133336632336265
33653362306333356230396137353265346661333038313662306237336237366432626665663236
38623963386334336466663035336435636263363931366631616432383331376139383031613034
64626633613666613237383262373862626639326133336139616335363936343061303134646332
64346231643734363561616638336464303665326566616130303163386537393535633661383939
38366362613833383861383563383365343538306131333862633833646563346364623564393938
3938
