$ANSIBLE_VAULT;1.1;AES256
61313133353938636138346462316161616661316166623563663765313566353138303032303530
6635306564336666306135653533656261653939633434650a366133653237623230633963333437
30663737616365383930306566386464626233623334666537393632663239386136663863373932
3466316561656631650a613961633738313364643237353061316231633362363265313138383634
66633739343139353366613832383161326433616664663339306338396433646437666332333637
35666464663932346436653437636364626235633463393762326539663762356135663864383761
34333565663337306563356237323965346333623466383664636437623034656138333733646638
63626266333437343232653134333036346637303161323266666162393565313734346632653937
31333666666139643639646261313932333834326362376135313939313936333462313264363732
39656664626562353834336366626538333636626539333939326431343962386461396463303761
65373364396363393138653662333439333732643236623831303834663564626562656565313566
61636165633662646461343566653835623138643638303635623963656136386464366561616564
33323131656664623233356337653436316239363863343063663931626138643161373331353533
30396132626265303533333533383966333933316533343334306361316435333162616563363938
62666265353631626439356364333563356362336462343833353330343738623136353133623264
66393939343437383537
