$ANSIBLE_VAULT;1.1;AES256
34376133336439656162363930353939306464636639613061303034383635636332643864343236
6364656633613030383164363961643765623764373830360a613435343031306433343435336466
36626365316462363662396235326561326535343962623139643863393365636436316131613738
3133306364386166340a363230313636386232386264306166393663613265306331646464323261
61316338383831663962353564353162356464393738303331353166366366616637316135646338
33616665313733326338366336613639363331376130313139343131323331613434363637303763
61393366333239663665396366313630353035393063656663653639613737333139306464643639
34636132393862376330
