$ANSIBLE_VAULT;1.1;AES256
32363738363334333031353335323132636662313435386432346632643333326630613532643935
3731363562616561393462366134616164336130303534300a353830663164616333623565333739
65616535646666333766613762633333636664613536346232663434313135363138396239663261
6165353637653461310a373166373030393134396630636661316432613063356633656362396430
34313138313132353962363537313632663763343139333639343564333833326234383966396262
34363034633635313339623866653161356332613432306133393961333566346231356665666365
34363363346231386637393235323532666635373366656532366263353361386139313634363734
39616466666663383236663561333461333538616234383332353133626566633063346333386239
66396164346439666437333939646539353662636432363463393436316466663464353639616261
36306530663730333062646336623130373239373334386338373032366164313436663966356639
36623062303535346662613561613932323836613932356537663030373233643533616438633735
32363763656562653765356563343734366162393366306466636339396365643832646262616338
31356131343133633464356632613535316261363532326363643533643936333336386361636461
62636132366465363138613363643064393737626661323539326338373064333230376330336438
393564376635656538616638396665623235
