---
all:
  children:
    bare_metal:
      hosts:
        airflow-1:
          ansible_host: 138.201.128.108
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        clickhouse-keeper-1:
          ansible_host: 88.99.97.49
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        clickhouse-keeper-2:
          ansible_host: 138.201.137.181
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        clickhouse-keeper-3:
          ansible_host: 136.243.150.84
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        clickhouse-replica-1:
          ansible_host: 94.130.13.115
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        clickhouse-replica-2:
          ansible_host: 88.99.151.102
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        data-science-staging-1:
          ansible_host: 88.99.192.144
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        dragonfly-db-1:
          ansible_host: 88.99.58.111
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        github-action-runner-1:
          ansible_host: 94.130.14.115
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        low-traffic-1:
          ansible_host: 138.201.131.107
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        milvus-1:
          ansible_host: 88.99.249.91
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        sentry-1:
          ansible_host: 88.99.160.251
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_timeout: 600
        storj-interface-1:
          ansible_host: 94.130.128.93
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        team-dev-server-1:
          ansible_host: 88.99.61.221
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        uptime-monitor-1:
          ansible_host: 138.201.22.251
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_python_interpreter: /usr/bin/python3
    kubernetes:

    staging:
      hosts:
        data-science-staging-1:
    development:
      hosts:
        team-dev-server-1:
