---
all:
  children:
    bare_metal:
      hosts:
        ai-chat-2:
          ansible_host: 94.130.38.82
        airflow-1:
          ansible_host: 138.201.128.108
        clickhouse-keeper-1:
          ansible_host: 88.99.97.49
        clickhouse-keeper-2:
          ansible_host: 138.201.137.181
        clickhouse-keeper-3:
          ansible_host: 136.243.150.84
        clickhouse-replica-1:
          ansible_host: 94.130.13.115
        clickhouse-replica-2:
          ansible_host: 88.99.151.102
        coolify-1:
          ansible_host: 136.243.20.189
        data-science-staging-1:
          ansible_host: 88.99.192.144
        dragonfly-db-1:
          ansible_host: 88.99.58.111
        github-action-runner-1:
          ansible_host: 94.130.14.115
        low-traffic-1:
          ansible_host: 138.201.131.107
        milvus-1:
          ansible_host: 88.99.249.91
        offchain-agent-1:
          ansible_host: 136.243.174.45
        offchain-agent-2:
          ansible_host: 116.202.245.32
        postgres-1:
          ansible_host: 162.55.88.112
        sentry-1:
          ansible_host: 88.99.160.251
          ansible_timeout: 600
        sentry-2:
          ansible_host: 138.201.129.173
          ansible_timeout: 600
        storj-interface-1:
          ansible_host: 94.130.128.93
        supabase-staging-1:
          ansible_host: 136.243.147.225
        team-dev-server-1:
          ansible_host: 88.99.61.221
        uptime-monitor-1:
          ansible_host: 138.201.22.251
        vault-1:
          ansible_host: 94.130.160.240
        vault-2:
          ansible_host: 88.99.242.238
        vault-3:
          ansible_host: 65.21.134.251
    staging:
      hosts:
        data-science-staging-1:
    development:
      hosts:
        team-dev-server-1:
