$ANSIBLE_VAULT;1.1;AES256
66626530643333633337336236336366626230316338306134303761383430373436363736396637
3565366364303065386133323730653838636632393732340a356438643034303533613137643231
66326162636561353363663435323366396433333139643238653730326330333537306638356262
3964636534373031340a613234303130323832623065336136656661313431373630656132623434
33656637396336336463653137343639313861376533633238633962306264656537313736626333
64666434653336656138323365356335363763373133653436623763356636336164306136393336
34306433373337313038663838386338336333353761653335636139353534623736633430373731
65313662333933623964333831313437346638663531623737643234363831346233653730653035
36613931393837666464353636643438353337343736373161613235643261376161316665636133
61633161366135393033633438306162643037326537303262366431616230653062613965653737
33323364353666626436373765303534363163316566613764303932366163616631303064663131
32633736383634383939326363623934616335623236323765383235643436643839333265613938
63613262373837343435386262303134666139356163626134386363626233366437306434623433
65623234373237393365623738386166353865383136316138383435386662343431613131653939
64303064363862306134343064336237373033393666393639303063663335663637346538343232
64613636303433613738613366323737393261646164393730306265623636336466366432346534
3861
