$ANSIBLE_VAULT;1.1;AES256
30386132643461386566666362656537303332646635633233313333653336663464343031653031
6530396564643961303762646339303664386465633035350a316433663331316134643633373265
39623338653931613438323139616630366232366236383563663263666239386231613062303838
6436613535653330630a616637343230323932306530323361643538653636383632353662623631
65656332333836653035363964383963393061326633383736353339303131313436616439363064
64353335663336353265373036653961616561303165393435336336333461636666643464666132
34326164623739383764666230346638316139313663343038303631393939376639623766646534
34333036313537356161663135623138336139313231333161373931653961613034313730393031
31623465373864323531373662343539633630396366386261366635306665383363616466633137
66306537653364356264333834643133333436383064343262343636383364313865653235633730
30666439303637646162316130623266313030316335363634326264613933343034386463613530
39336261386264366231633631346536353263396533356362386530663463373961316638306561
34303133396566393539623464363437363764383732393063666636356661333461333862376636
33333635633962616565313534313636313136303733643563313965343562613239663134663866
39613563353365623333376664313462613432386339393235666135353964383062643331386566
39326266346331316135
