$ANSIBLE_VAULT;1.1;AES256
32646132396261626463363236396464656337343562663636383864613564633161316237313933
3335323838663339653964326263356531306437636262360a303661303632303334373765656363
66663763303766326632353230303630613664613462303466656461363166653664386537353338
3339633134623530380a386433366132313961313765643832663563333066346230326531636162
63613538396364333337343033303563626337323763313935636465383664633231666138373134
65613338633439376636626538396635346136383461663563353664396137313065373362613134
63666666313764613732366435343065356234623233653436373763333964663936306263326436
33326430323933616362306338663230653565343830356466626234333533356364613233376338
64393830346564363937346464666333313834383864386231336131313164653763313863336135
38663834633866326335313235306436323861626131663831383161383434643164346163336535
35666337626236313334356335346366633733353234316435663762313435656335386431656136
38636163613330383331356134653637346339643766353431333734616261623138356237353635
31623830353038386664656163346234386563313337333566633464366538663636386632613764
3064323664613233646464323030346266336536663535343235
