$ANSIBLE_VAULT;1.1;AES256
66333237326234383063643134356636613964306232393933333438653934313061653033363662
6339383164656338336635373638613938376638336234650a316138376464356631333334616665
65326238616161333162383166623037396433386431336435306432306266623735366437366261
3565326634633938380a636639303963313865623835386638633634316563666666323762343636
62656164343937303535626666356666323937623134303234363166643664346435376134333037
62613963646362633961383133313638356635373264373734313733613735303564383462376331
66386638376436303166653339626432383139633534666562633236653865363735653864306361
35313935653534356462623339343539613064373061646666366662363664366166316634363465
33633763373234396332386365333465633366636536353737343865383536393039323231656331
31383465383033616639343735633939333862663239633638646233633363356462626532393363
61396164363664356263303633323435393966663337313463303538653433353465393233306137
64306635653637303033356562633838666633326536386566663233373865643032303134353062
63393636633261623334613466626431383435333163356439643930623265313031353766353563
39313237373236393032393234393662326531653539633932326561313463626438363063363061
38313230316162646434636131666634333266643264356135616332316131376633626564643430
61336361666536376362
